
services:
  java_db:
    image: mysql:9.0
    restart: always
    container_name: java_db
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3308:3306
  adminer:
    image: adminer:4.8.0-standalone
    container_name: adminer-4.8.0-standalone
    restart: always
    ports:
      - 8081:8080